import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import HeaderClerk from "@/components/HeaderClerk";
import HeaderFallback from "@/components/HeaderFallback";
import Footer from "@/components/Footer";
import BottomBar from "@/components/BottomBar";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

  const content = (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
        <main className="min-h-screen flex flex-col justify-between">
          <div>
            {clerkPublishableKey ? <HeaderClerk /> : <HeaderFallback />}
            {children}
          </div>
          <Footer />
          <BottomBar />
        </main>
        <SanityLive />
      </body>
    </html>
  );

  // Provide a safe fallback publishable key so client hooks don't throw during build.
  const publishableKey = clerkPublishableKey ?? "local_fallback_publishable_key";

  return <ClerkProvider publishableKey={publishableKey} dynamic>{content}</ClerkProvider>;
}
